### ISSUE TITLE
网络带宽建议固定显示小数点后1~2位即可

### ISSUE THREAD

**Issue by inhowe** [nexmoe/vscode-monitor-pro#25]

**Comment by inhowe** [comment]
这种情况切换单位就可以了吧？
100B/s
100.12KB/s
100.12MB/s



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Nexmoe ***@***.***&gt;
发送时间: 2024年5月10日 11:09
收件人: nexmoe/vscode-monitor-pro ***@***.***&gt;
抄送: Inhowe.Yue ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [nexmoe/vscode-monitor-pro] 网络带宽建议固定显示小数点后1~2位即可 (Issue #25)





 
不合理，那么百兆就无法显示了

**Comment by nexmoe** [comment]
目前的机制是保持四位数字和一个.
100B/s
100.12KB/s
100.12MB/s
会导致布局跳动
