### ISSUE TITLE
建议：固定CPU Usage显示的数字（<1%时）

### ISSUE THREAD

**Issue by ZZYSonny** [nexmoe/vscode-monitor-pro#31]
目前CPU Usage似乎会固定显示3位有效数字。
如果CPU的核心比较多，负载比较低的时候，CPU Usage会显示超过3个数字，负载一高，又只会显示三个数字。导致底下布局变化。
建议在负载<1时，固定显示0.xx。

![image](https://github.com/nexmoe/vscode-monitor-pro/assets/28442838/03893364-d7c1-454f-a044-8e728ef50d6e)
![image](https://github.com/nexmoe/vscode-monitor-pro/assets/28442838/fc40d270-f3ba-49b7-9539-453f2dad117c)

**Comment by nexmoe** [comment]
CPU 应该就是固定的

https://github.com/nexmoe/vscode-monitor-pro/blob/4c9715f6dd2e5703554860c05b81b1af2270d341/src/metrics.ts#L18-L24
