### ISSUE TITLE
CPU Usage doesn't match the task manager figure in Windows.

### ISSUE THREAD

**Issue by xuestrange** [nexmoe/vscode-monitor-pro#4]
The CPU Usage is relatively lower than the figure in task manager in Windows 10. I guess the reason should be that this extension uses the processor time to measure it. To align with the figure in Windows task manager, a better metric is by the performance counter. Another extension [Resource Monitor](https://github.com/Njanderson/resmon.git) also mentioned such phenomenon.

**Comment by nexmoe** [comment]
Data is from https://github.com/sebhildebrandt/systeminformation. 
You can do some research.
